### ISSUE TITLE
Declarative examples go out of sync due to API version changes post CAPI upgrades

### ISSUE THREAD

**Issue by Rohitrajak1807** [arlonproj/arlon#439]
The cluster app in ArgoCD goes out of sync with capi version 1.3.2 and capa 2.0.2(latest)

The pre-prepped cluster template in `examples/clustertemplates/eks-managed-mpool/manifest.yaml` needs to switch from the `v1beta1` to `v1beta2` of `apiVersion` for kinds `AWSManagedControlPlane` and `AWSManagedMachinePool` .
The `spec.infrastructureRef.apiVersion` and `spec.confrolPlaneRef.apiVersion` for kind `Cluster` needs to change from `v1beta1` to `v1beta2`.

On running `clusterctl generate` we get an additional object which is missing from the example:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: capi-quickstart
  namespace: default
spec: {}
```
TODOs:
1. Switch to proper apiVersions
2. Examine if the missing `infrastructure.cluster.x-k8s.io/v1beta2/AWSManagedCluster` object also results in an out of sync cluster app.

Aha! Link: https://pf9.aha.io/features/ARLON-392
